### ISSUE TITLE
Unable to parse cyrillic characters

### ISSUE THREAD

**Issue by arturi** [valeriangalliat/markdown-it-anchor#10]
Just skips them for the first one (and adds negative numbers to others):

<img width="927" alt="screen shot 2015-09-22 at 23 40 22" src="https://cloud.githubusercontent.com/assets/1199054/10031014/658b79a6-6183-11e5-9f95-04abf4aa6f9a.png">

**Comment by arturi** [comment]
It’s a unicode RegEx and string.js’s problem: https://github.com/jprichardson/string.js/issues/43

**Comment by arturi** [comment]
Ended up writing my own slugify function like this:

```
slugifyHeaderId: function (s) {
    return s.trim()
       .toLowerCase()
       .replace(/\s\s+/g, ' ')
       .replace(/[^\w\s\u0400-\u04FF-]/g, '')
       .replace(/\s/g, '-')
       .toString();
  },
```

**Comment by valeriangalliat** [comment]
Yeah I guess it's a problem with strings.js, and I don't wanna take position on this personnally... I hope you're fine with your own slugify function, that's also why I made it configurable after all!
