### ISSUE TITLE
Headings containing a hashtag yield invalid hrefs 

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [valeriangalliat/markdown-it-anchor#103]
One thing I noticed today is that one of my pages is giving me HTML validation errors because it has a heading of the form:

```markdown
# Approach #1: Do something
```

And that nested hashtag yields this invalid anchor URL:

```
#approach-#1-do-something
```

Would it be possible to remove this special character from the output href since it's not allowed to appear more than once?

**Comment by valeriangalliat** [comment]
Hey! We use `encodeURIComponent` as the defaut `slugify` function so out of the box your example should output:

```html
<h1 id="approach-%231%3A-do-something" tabindex="-1">Approach #1: Do something</h1>
```

Did you customize the `slugify` function? Also what HTML validator are you using?

**Comment by AleksandrHovhannisyan** [comment]
Ah, that explains it! Yes, I customized it, and my custom slugify function wasn't handling that character. Thanks for the super quick response!
