### ISSUE TITLE
incorrect type for permalink.headerLink()

### ISSUE THREAD

**Issue by benblazak** [valeriangalliat/markdown-it-anchor#108]
https://github.com/valeriangalliat/markdown-it-anchor/blob/7a64eec879b7f1617800680ef87e5ac6235ed79a/types/index.d.ts#L56

Should probably allow for options, like the other types nearby.

TypeScript complains e.g. about `permalink: MarkdownItAnchor.permalink.headerLink({ safariReaderFix: true })`.

Workaround: Put a `// @ts-ignore` above the line.

**Comment by valeriangalliat** [comment]
Thanks for reporting! I just fixed this in v8.6.1 so you can remove your `// @ts-ignore`. Sorry for the late reply :)

**Comment by benblazak** [comment]
thanks!
