### ISSUE TITLE
Feature request: container option for linkAfterHeader

### ISSUE THREAD

**Issue by JanDW** [valeriangalliat/markdown-it-anchor#110]
Hi Val, 

I noticed that to add a container around the outputted HTML when using`linkAfterHeader` I'd need to implement my [own render function](100).  Would it make sense to provide an option for passing in a container?

Best,

Jan

**Comment by valeriangalliat** [comment]
Hey! Seems like a common demand for `linkAfterHeader` to include a wrapper in the output, @nhoizey also wanted to do this in #100. I came up with a proposal solution in #111, it looks like this:

```js
const anchor = require('markdown-it-anchor')
const md = require('markdown-it')()

md.use(anchor, {
  permalink: anchor.permalink.linkAfterHeader({
    style: 'visually-hidden',
    assistiveText: title => `Permalink to “${title}”`,
    visuallyHiddenClass: 'visually-hidden'
    visuallyHiddenClass: 'visually-hidden',
    wrapper: ['<div class="wrapper">', '</div>']
  })
})
```

```html
<div class="wrapper">
  <h2 id="title">Title</h2>
  <a class="header-anchor" href="#title">
    <span class="visually-hidden">Permalink to “Title”</span>
    <span aria-hidden="true">#</span>
  </a>
</div>
```

Does this looks like a reasonable API?

Cheers!

**Comment by JanDW** [comment]
[There are more of us.](https://11ty.rocks/eleventyjs/slugs-anchors/) :)

>Does this looks like a reasonable API?

Yes, that was exactly what I was hoping for—thanks!

**Comment by valeriangalliat** [comment]
Awesome, published with v8.5.0! Thank you for the Ko-fi :heart:

**Comment by JanDW** [comment]
Thank you! 🏅

**Comment by nhoizey** [comment]
I'm late using this, but it rocks! Thanks @valeriangalliat
