### ISSUE TITLE
Add brief description of what plugin does to top of readme.

### ISSUE THREAD

**Issue by Tolu-Mals** [valeriangalliat/markdown-it-anchor#117]
I came across this plugin while studying a codebase and it's really difficult to understand what this plugin does. I suggest that there's a brief description of what this plugin does at the top of the readme to help people like me learning about it for the first time.

I suggest "A [markdown-it](https://github.com/markdown-it/markdown-it) plugin that adds an `id` attribute to headings"(as the readme in [markdown-it-headinganchor](https://github.com/adam-p/markdown-it-headinganchor) puts it). A more detailed description would be more helpful though.

That's the best description I can come up with as I still have a rough understanding of  what this plugin does. I'll be glad to create a pull request if you resonate with this idea as well.

**Comment by valeriangalliat** [comment]
That's a great suggestion! I just updated the readme in https://github.com/valeriangalliat/markdown-it-anchor/commit/5bbb52016c13ec48df3754093fc3e15cff5a4c3a to include a more comprehensive overview =) don't hesitate to suggest any other improvements if I missed anything!
