### ISSUE TITLE
Query: How do I attach a class to the header element?

### ISSUE THREAD

**Issue by realChakrawarti** [valeriangalliat/markdown-it-anchor#132]
Thank you for the amazing work.

I went through the documentation/README but couldn't find a way to attach a class to the header element where id is injected.

Here is my existing implementation:

```js
  md.use(anchor, {
    tabIndex: false,
    slugify: (s: string) => slugify(s),
    permalink: anchor.permalink.headerLink(),
  });
``` 
which outputs as expected.

```html
<h2 id="example-id"><a class="header-anchor" href="#example-id">Example ID</a></h2>
```

But I want something like:
```html
<h2 id="example-id" class="hardcoded"><a class="header-anchor" href="#example-id">Example ID</a></h2>
```

The reason for this to add `scroll-margin-top`, as due to fixed header, the heading element remains hidden.

If there any workaround to do the same, please do let me know. Thanks.

**Comment by valeriangalliat** [comment]
Hi!

There's no such option at the moment however you can leverage the `callback` argument to implement that easily!

The `callback` gets passed the markdown-it `Token` object for every heading element that gets processed, so you can use that to append a class to it:

```diff
   md.use(anchor, {
     tabIndex: false,
     slugify: (s: string) => slugify(s),
     permalink: anchor.permalink.headerLink(),
+    callback: (token) => token.attrJoin('class', 'hardcoded'),
   });
```

Cheers :)

**Comment by realChakrawarti** [comment]
This worked. Thank you. Closing the issue.
