### ISSUE TITLE
Bigfoot.js Footnotes Broken

### ISSUE THREAD

**Issue by ToniWonKanobi** [valeriangalliat/markdown-it-anchor#2]
[Bigfoot.js][bf] is a JavaScript tool used to render footnote popups in lieu of regular-style 'bounce-around-the-page' footnotes. 

I am using [Casey Liss][cl]'s node-based blogging engine [Camel][cm], and have found that when viewing the source for a rendered page, the footnote placeholders become `<undefined>` in the HTML. 

Here is a snippet parsed HTML showing the `<undefined>` element, in the place of where a footnote identifier/class *should* be.

```html
<li id="fn10"  class="footnote-item"><undefined>And the pictures in the article only show the flappy box <a href="#fnref10" class="footnote-backref">↩</a><undefined></li>
```

Ideas?

[bf]: http://www.bigfootjs.com
[cl]: http://www.twitter.com/caseyliss
[cm]: https://github.com/cliss/camel

**Comment by valeriangalliat** [comment]
Hi,

Can you give a sample project and the steps to reproduce the bug?

And what's the relation between markdown-it-anchor and this `<undefined>` tag?

**Comment by ToniWonKanobi** [comment]
Sorry. There was an issue with a package dependency that caused Bigfoot footnotes to break. Closing! :)
