### ISSUE TITLE
2.5.1 and newer are not tagged, no release notes exist

### ISSUE THREAD

**Issue by ticky** [valeriangalliat/markdown-it-anchor#25]
I’ve just found that 3.0.0 is out, however, I can’t find any reference to any changes, and I can’t seem to glean from the commit history exactly what’s changed. 2.5.1 and up are also missing from tags, so I can’t tell what changed between them either.

Is 3.0.0 really a major API change?

**Comment by valeriangalliat** [comment]
Thanks for the heads up @ticky, forgot to update the changelog after bumping 3.0.0.

I just updated the [changelog](https://github.com/valeriangalliat/markdown-it-anchor/blob/master/CHANGELOG.md#300---2017-02-06) so you can see what's new.

And yes 3.0.0 is a major API change in the sense that it makes markdown-it-anchor drop support for markdown-it 5 and lower.

**Comment by caraya** [comment]
Are you releasing versions to NPM? When I try to install from npm using `npm i -D markdown-it-abbr@latest` the version I get is 1.0.4

**Comment by valeriangalliat** [comment]
@caraya I do, you're on the markdown-it-anchor repo and the latest version is 4.0.0.

For markdown-it-abbr, you should look at this repo <https://github.com/markdown-it/markdown-it-abbr>, but it seems that 1.0.4 is indeed the latest version for markdown-it-abbr.
