### ISSUE TITLE
GitHub inspired permalink rendering

### ISSUE THREAD

**Issue by niftylettuce** [valeriangalliat/markdown-it-anchor#28]
If possible, could we get permalinks to render just like GitHub does for Readme's?

e.g. the hover and the entire header is a link itself?

**Comment by valeriangalliat** [comment]
On GitHub readmes, as far as I can see, the anchor appears when you hover on the header, but only the anchor icon is a link itself. markdown-it-anchor behaves this way too.

You might want to set `{ permalink: true, parmalinkBefore: true }` in markdown-it-anchor options to make it look more like GitHub. Example: https://www.codejam.info/2015/05/batch-updating-npm-packages-license.html
