### ISSUE TITLE
How to add prefix to id?

### ISSUE THREAD

**Issue by oztek22** [valeriangalliat/markdown-it-anchor#29]
In your documentation you mentioned that by using slugify we can create custo id but it uses jquery.
SO I wonder is there any way to add custom prefix to Id?

**Comment by valeriangalliat** [comment]
It doesn't use jQuery, it uses the [string.js](http://stringjs.com/#methods/slugify) module.

If you want to add a custom prefix, you can do the following:

```js
const markdownItAnchor = require('markdown-it-anchor')

const md = require('markdown-it')()
  .use(markdownItAnchor, {
    slugify: s => `prefix-${markdownItAnchor.defaults.slugify(s)}`
  })
```
