### ISSUE TITLE
Lambda function breaks minifying

### ISSUE THREAD

**Issue by dreadcast** [valeriangalliat/markdown-it-anchor#34]
Hi there,

I successfully use _markdown-it-anchor_ until I try to make a production build using Webpack, along with [UglifyJS plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin).

```
ERROR in dashboard.js from UglifyJs
Unexpected token: operator (>) [dashboard.js:98703,19]
```

I think I've identified what breaks minifying: the use of lambda functions (`() => {}`)

Shouldn't this package be available as a 100% ES5 version ?

**Comment by valeriangalliat** [comment]
Isn't it minifying that breaks dependencies?

**Comment by dreadcast** [comment]
Nope, lambda functions are not broken, UglifyJS just does not support ES6 code. I've tried several options to replace Webpack UglifyJS plugin, without success :(

Lastly, I [cloned](https://github.com/dreadcast/markdown-it-anchor/tree/es5) and (manually) transpiled your code to ES5, it works finely.

**Comment by valeriangalliat** [comment]
Oh right, I think you should us [uglifyjs-es](https://github.com/mishoo/UglifyJS2/tree/harmony) then!

But if you're shipping the minified code to environments that still doesn't support ES5, your solution of transpiling it is still right... it's up to you!

**Comment by dreadcast** [comment]
I've tried uglifyjs-es, but could not get it to work with my Webpack version and conf.

I'll consider this option on my next big update !
