### ISSUE TITLE
feature: add token.tag to callback

### ISSUE THREAD

**Issue by HenrikBechmann** [valeriangalliat/markdown-it-anchor#37]
... this would allow the caller to organize a table of contents with depth
```
          opts.callback(token, { slug, title, tag:token.tag })
```

**Comment by nagaozen** [comment]
Hey @HenrikBechmann, could you please explain further your request? I don't get why `info.tag` is better than `token.tag` in the `cbf(token, info)` call.

**Comment by HenrikBechmann** [comment]
In hindsight, I agree.
