### ISSUE TITLE
TypeError: linkTokens[position[(!opts.permalinkBefore)]](...) is not a function

### ISSUE THREAD

**Issue by buddh4** [valeriangalliat/markdown-it-anchor#39]
I've added this plugin to my rollup build (by npm) and I get the following error when enabling the permlinks:

```
TypeError: linkTokens[position[(!opts.permalinkBefore)]](...) is not a function
```

This happens in line https://github.com/valeriangalliat/markdown-it-anchor/blob/master/index.js#L33

The rollup output of those lines are:

```
linkTokens[position[!opts.permalinkBefore]](space())
(ref = state.tokens[idx + 1].children)[position[opts.permalinkBefore]].apply(ref, linkTokens);
```

a simple semicolon after the first line would solve this issue:

```
linkTokens[position[!opts.permalinkBefore]](space());
```

**Comment by nagaozen** [comment]
@buddh4, are you still experiencing this? According to the project linter [standard](https://standardjs.com/), this extra semicolon isn't required.

**Comment by buddh4** [comment]
Haven't tried it since then. I've just added the file manually for now with the extra semicolon. I assume its rather a rollup issue.

**Comment by nagaozen** [comment]
Thank you
