### ISSUE TITLE
Anchor links only working in chrome

### ISSUE THREAD

**Issue by stelabr** [valeriangalliat/markdown-it-anchor#42]
For some reason, the anchor links are only working properly in chrome. When I test in Firefox or Safari, the page is scrolled to the top.

**Comment by nagaozen** [comment]
Hi @stelabr, could you please provide some evidence of this? We cannot reproduce your issue. A [jsfiddle](https://jsfiddle.net/) or [codepen](https://jsfiddle.net/) would be awesome for testing your code.

**Comment by nagaozen** [comment]
No evidence provided or how to reproduce the bug.
