### ISSUE TITLE
not support  Chinese language

### ISSUE THREAD

**Issue by ideagay** [valeriangalliat/markdown-it-anchor#43]
.md
`## [# 添加权限](#ss)`
result
`<h2><a href="#ss"># 添加权限</a></h2>`

.md
`## [# 添加权限role](#ss)`
result
`<h2 id="role-2"><a href="#ss"># 添加权限role</a></h2>`

is there a way to solve？

**Comment by nagaozen** [comment]
Fixed by version `5.0.0`.
