### ISSUE TITLE
High vulnerability error on "npm audit"

### ISSUE THREAD

**Issue by Manvel** [valeriangalliat/markdown-it-anchor#44]
Currently running "npm audit" on/with current package shows high vulnerability error.

See image below:
<img width="731" alt="screen shot 2018-06-05 at 9 53 29 pm" src="https://user-images.githubusercontent.com/716969/40993820-a8fd55c8-690b-11e8-9ace-84f65e8f93df.png">

[Relevant issue in the string repo](https://github.com/jprichardson/string.js/issues/212).

**Comment by nagaozen** [comment]
Fixed by version `5.0.0`.
