### ISSUE TITLE
BUG: Table of contents does not support markdown 

### ISSUE THREAD

**Issue by coryschires** [valeriangalliat/markdown-it-anchor#48]
## Scenario
Given I have the following markdown string:

    [[toc]]

    # Introduction to American Novels
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod 
    tempor incididunt ut labore.

    ## Literary Analysis of _Catcher in the Rye_ 
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod 
    tempor incididunt ut labore.

    ## Understanding Race in *Huckleberry Finn*
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod 
    tempor incididunt ut labore.

This will render the following table of contents:

      <div class="table-of-contents">
        <ul>
          <li>
            <a href="#introduction-to-american-novels">Introduction to American Novels</a>
            <ul>
              <li><a href="#literary-analysis-of-catcher-in-the-rye">Literary Analysis of _Catcher in the Rye_</a></li>
              <li><a href="#understanding-race-in-huckleberry-finn">Understanding Race in *Huckleberry Finn*</a></li>
            </ul>
          </li>
        </ul>
      </div>

      <h1 id="introduction-to-american-novels">Introduction to American Novels</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore.
      </p>
      
      <h2 id="literary-analysis-of-catcher-in-the-rye">Literary Analysis of <em>Catcher in the Rye</em></h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore.
      </p>
      
      <h2 id="understanding-race-in-huckleberry-finn">Understanding Race in <em>Huckleberry Finn</em></h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore.
      </p>

## Problem
Notice that the ToC headers contain raw / unprocessed markdown (e.g. `Literary Analysis of _Catcher in the Rye_`) whereas the actual headers have converted the markdown into HTML (e.g. `Literary Analysis of <em>Catcher in the Rye</em>`).

I would expect to see the markdown be converted into HTML in both locations.

## Next steps
Looking at your code, I _think_ the `md` object may have access to the underlying rendering functions. For example, I wrote a markdown-it extension which did something like:

    this.env.md.renderInline("Some text which _may have formatting_")

And this allowed me to process markdown text within my extension – which I think is what we want in this case as well.

I'm not 100% sure how this would work in your code, but I think it's possible (and probably pretty easy). If you need help, lemme know and could probably make a PR.

**Comment by coryschires** [comment]
Shoot. This issue was intended for [markdown-it-table-of-contents](https://github.com/Oktavilla/markdown-it-table-of-contents). 

Sorry about this mixup. Closing!

**Comment by nagaozen** [comment]
Ok, by the way, if you are struggling with that plugin, you may try instead: [markdown-it-toc-done-right](https://www.npmjs.com/package/markdown-it-toc-done-right).
