### ISSUE TITLE
respect customised id with markdown-it-attrs?

### ISSUE THREAD

**Issue by naivefun** [valeriangalliat/markdown-it-anchor#49]
I'm using markdown-it-attrs and I'd like to assign id to header. But anchor will overwrite the id, is it possible to ignore id slug when an id is already in place?

**Comment by nagaozen** [comment]
Hum, seems to be right thing to do.

**Comment by naivefun** [comment]
@nagaozen actually I just find out it is there already    
https://github.com/valeriangalliat/markdown-it-anchor/blob/1cc288c84ddac11a7047f2adb301b6958929ff19/index.js#L64-L66

I just need put this extension AFTER attrs 😸
