### ISSUE TITLE
Use md.core.ruler to add attributes, so that they can be used by other plugins.

### ISSUE THREAD

**Issue by arve0** [valeriangalliat/markdown-it-anchor#5]
Hi!
Any particular reason [you use `md.renderer`](https://github.com/valeriangalliat/markdown-it-anchor/blob/master/index.es6.js#L56) instead of [`Token.attrPush`](https://markdown-it.github.io/markdown-it/#Token.attrPush)?

The reason I ask, is because it would be nice to have access to the `id` attribute from other plugins. Like the one I'm creating now: https://github.com/arve0/markdown-it-header-sections/blob/master/index.js#L17

**Comment by valeriangalliat** [comment]
Hi,

Well, the particular reason was I didn't knew about `Token.attrPush`!

But isn't the line `;(tokens[idx].attrs = tokens[idx].attrs || []).push(['id', slug])` a "manual" `Token.attrPush`?

I'm still not sure how to modify the code to use `Token.attrPush` instead of `md.renderer`, would you be okay to make a PR?

**Comment by arve0** [comment]
It might not been around when you made this plugin, it was [added March 7](https://github.com/markdown-it/markdown-it/commit/37308209459963de922e0eb4df8eb2369314ccf2).

I'll look into your code a bit more in depth, and see if a refactor is possible.

**Comment by arve0** [comment]
Ah! As you mention, attributes are added, but they are added when rendering. Would you accept a PR that adds the attributes as a step in md.core.ruler?

**Comment by valeriangalliat** [comment]
Absolutely!

**Comment by valeriangalliat** [comment]
Fixed with 2.2.0!

**Comment by arve0** [comment]
Thanks for the quick response :octocat:
