### ISSUE TITLE
Repeated problem with anchor

### ISSUE THREAD

**Issue by cbbfcd** [valeriangalliat/markdown-it-anchor#56]
version: v5.0.1
device：macbook pro
description:
Using the markdown-it-anchor plugin and tui-editor combined, using react, when publishing the edited content, it is found that each release adds an anchor.
```javascript
tui.Editor.markdownit.use(
    mdAnchor,
    {
        level: [1, 2, 3, 4, 5, 6],
        permalink: true,
        permalinkSymbol: '#',
        slugify: s => slug(s)
    }
);
```
As shown in the figure below, multiple anchors will be generated, but I only need one.

![Z7nlMd.png](https://s2.ax1x.com/2019/07/16/Z7nlMd.png)

I found the problem is that when you execute renderPermalink , you will continue to add anchors. So, is there any good solution?

**Comment by nagaozen** [comment]
Could you explain further the problem? What's the input for the markdown-it?

**Comment by cbbfcd** [comment]
ok，The approximate process is like this：

1. a tui-editor instance with the anchor plugin:
```js
const Editor = require('tui-editor');

[the editor integrated markdownit](https://nhn.github.io/tui.editor/api/latest/ToastUIEditor.html#.markdownit)

const md = Editor.markdownit(
  require('markdown-it-anchor'),
  {
    level: [1, 2, 3, 4, 5, 6],
    permalink: true,
    permalinkSymbol: '#',
    slugify: s => slug(s)
  }
);

// output the edtior = new Editor()
```

2. Click the Publish Article button on the edit page.

```js
// 1. get the current markdown string by editor api [hehre](https://nhn.github.io/tui.editor/api/latest/ToastUIEditor.html#getMarkdown)
const markdown = edtior.getMarkdown();
const html = editor.getHtml();

// getHtml is actually md.render(markdown);
```

3. when i update somthing in the article, and re-pulish the article, i found the anchor be added one more. as the issue picture show.

**Comment by cbbfcd** [comment]
i found the reason, it's my stupid error. sorry and thanks
