### ISSUE TITLE
Specifying a base URL in a Nuxt app breaks the links

### ISSUE THREAD

**Issue by lobo-tuerto** [valeriangalliat/markdown-it-anchor#59]
Hello,

After doing something like this in `nuxt.config.js`:

```js
router: {
    base: process.env.NODE_ENV === 'production'
      ? '/zeta/'
      : '/'
  }
```

All header anchors break and direct the user to the root of the app.
Is there anything I can configure so it works as it should?

Live article that exhibits the behaviour:
https://lobotuerto.com/zeta/blog/vuejs-components-inside-markdown

Try clicking on anything on the TOC, or the § links besides the headers in the main content.

**Comment by lobo-tuerto** [comment]
It even breaks in dev mode too, with `'/'` or `''` as base.

**Comment by nagaozen** [comment]
404 Not Found - Also, Nuxt is **downstream**.

**Comment by Atinux** [comment]
Actually, this is a browser issue directly: https://rogerkeays.com/blog/using-base-href-with-anchors

You can take a look at this workaround: https://github.com/nuxt/content/issues/376#issuecomment-702193217
