### ISSUE TITLE
TypeError: plugin.apply is not a function at MarkdownIt.use

### ISSUE THREAD

**Issue by jie12366** [valeriangalliat/markdown-it-anchor#61]
I have the problem when I use it.

**Comment by nagaozen** [comment]
Could you please explain further your problem? With examples et cetera

**Comment by jie12366** [comment]
I had resolve the problem using the following method.
![image.png](https://i.loli.net/2019/10/21/PXevupH5Wx8oU6j.png)
I use the es5 syntax.
