### ISSUE TITLE
Duplicated Headers generates wrong anchor links (incremented by 1)

### ISSUE THREAD

**Issue by LeonnardoVerol** [valeriangalliat/markdown-it-anchor#66]
## Bug report

When creating duplicated headers, is it expected that the duplicated anchor links will increase starting from "xxxx-1".
It starts from "xxxx-2".

#### Steps to reproduce

Create duplicated Headers (same name) inside a markdown file
```
# header

# header

# header
```

#### What is expected?
The anchor link for each header should be:
```
#header
#header-1
#header-2
```

#### What is actually happening?
It is generating the following anchor links:
```
#header
#header-2
#header-3
```

**Comment by nagaozen** [comment]
Not a bug. It's working as expected.
