### ISSUE TITLE
How to work in Angular

### ISSUE THREAD

**Issue by lhf552004** [valeriangalliat/markdown-it-anchor#71]
Hi,
Is it possible to work in Angular?
I did this below:
`
import * as MarkdownAnchor from 'markdown-it-anchor';
`
But it doesn't work when running.

**Comment by nagaozen** [comment]
I'm sorry, I didn't get your question. What's special about Angular? This library is supposed to be framework agnostic. As long it's leveraging javascript it should work. Could you please try the following codes and re-open the issue if your error persists?

```js
import MarkdownIt from 'markdown-it';
import MarkdownItAnchor from 'markdown-it-anchor';

const md = new MarkdownIt();
md.use(MarkdownItAnchor);
const content = `
# Hello World

## Lorem Ipsum
`;

console.log( md.render(content) )
```
