### ISSUE TITLE
Update readme for use in browser 

### ISSUE THREAD

**Issue by rammygit** [valeriangalliat/markdown-it-anchor#73]
There is a browserified global for use in browser. 

https://wzrd.in/standalone/markdown-it-anchor@latest

This link is pulled in from the demo in JSFiddle 

https://jsfiddle.net/9ukc8dy6/

**Comment by codekandis** [comment]
Generally it would be nice to have a non-nodejs release asset available. I really like to use it in my website.

**Comment by nagaozen** [comment]
Done
