### ISSUE TITLE
Quadratic complexity

### ISSUE THREAD

**Issue by stereobooster** [valeriangalliat/markdown-it-anchor#80]
```js
 tokens
      .filter(token => token.type === 'heading_open')
      .filter(token => isLevelSelected(Number(token.tag.substr(1))))
      .forEach(token => {
        // Aggregate the next token children text.
        const title = tokens[tokens.indexOf(token) + 1]
```

this operation is quadratic (`O(n!)`) - it will iterate over tokens, then for each token it will iterate again (`tokens.indexOf`)

Potential solution:

```js
tokens
      .forEach((token, i) => {
            if (token.type !== 'heading_open') return;
            if (!isLevelSelected(Number(token.tag.substr(1)))) return;
            // Aggregate the next token children text.
            const title = tokens[i + 1]
```

**Comment by valeriangalliat** [comment]
That's a good idea, wanna make a PR for it? Or if you prefer I'll just push your proposed solution, up to you :)

**Comment by stereobooster** [comment]
I guess it would be easier if you do it yourself - using your preferred code style. Maybe you would want to reinterpret it somehow

**Comment by valeriangalliat** [comment]
Sounds good! It's live with 7.0.2 :D
